"""
chat_manager.py

Centralized chat session manager used by the backend to maintain
conversation state for each user.

Responsibilities
----------------
1. Store original process graphs extracted from user input.
2. Store optimized process graphs generated by the optimizer.
3. Maintain chat history for follow-up questions.
4. Build conversation context for LLM prompts.
5. Create and manage isolated user sessions.
6. Provide thread-safe access to session data.

This module is intended to be used as an in-memory session store.
"""

from dataclasses import dataclass, field
from datetime import datetime
from threading import Lock
from typing import Optional
import json
from openai import AsyncOpenAI


# ==========================================================
# Chat message model
# ==========================================================
@dataclass
class ChatMessage:
    """
    Represents a single message exchanged during a conversation.

    Attributes
    ----------
    role : str
        Role of the sender ("user" or "assistant").

    content : str
        Actual message text.

    timestamp : datetime
        UTC timestamp when the message was created.
    """

    role: str
    content: str
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class UserSession:
    """
    Stores all information associated with a user.

    Attributes
    ----------
    user_id : str
        Unique identifier for the user.

    original_process_graph : Optional[list[dict]]
        Process graph extracted from the original input.

    optimized_process_graph : Optional[list[dict]]
        Optimized process graph produced by the optimizer.

    chat_history : list[ChatMessage]
        Previous conversation messages used to answer
        follow-up questions.
    """

    user_id: str
    original_process_graph: Optional[list[dict]] = None
    optimized_process_graph: Optional[list[dict]] = None
    chat_history: list[ChatMessage] = field(default_factory=list)


class ChatManager:
    """
    Manages user sessions and conversation memory.

    Features
    --------
    - Thread-safe session creation.
    - Storage of original process graphs.
    - Storage of optimized process graphs.
    - Conversation memory.
    - Context generation for LLM prompts.
    - Session cleanup.

    Notes
    -----
    Data is stored in memory and will be lost when the
    application restarts. For persistence, a database or
    Redis cache should be used.
    """

    def __init__(self):
        """
        Initialize the chat manager.

        Attributes
        ----------
        sessions : dict[str, UserSession]
            Maps user IDs to their corresponding session.

        lock : Lock
            Ensures thread-safe session creation and deletion.
        """
        self.sessions: dict[str, UserSession] = {}
        self.lock = Lock()

        self.client = AsyncOpenAI()
        self.model = "gpt-4o-mini"

    ##########################################################
    # Session handling
    ##########################################################

    def get_session(self, user_id: str) -> UserSession:
        """
        Retrieve an existing session or create a new one.

        Parameters
        ----------
        user_id : str
            Unique identifier for the user.

        Returns
        -------
        UserSession
            Session object corresponding to the user.
        """
        with self.lock:

            if user_id not in self.sessions:
                self.sessions[user_id] = UserSession(user_id=user_id)

            return self.sessions[user_id]

    ##########################################################
    # Original graph
    ##########################################################

    def update_original_graph(self, user_id: str, graph: list[dict]):
        """
        Store the original process graph for a user.

        Parameters
        ----------
        user_id : str
            User identifier.

        graph : list[dict]
            Original process graph extracted from input.
        """
        session = self.get_session(user_id)
        session.original_process_graph = graph

    def get_original_graph(self, user_id: str) -> Optional[list[dict]]:
        """
        Retrieve the original process graph.

        Parameters
        ----------
        user_id : str
            User identifier.

        Returns
        -------
        Optional[list[dict]]
            Original process graph or None.
        """
        return self.get_session(user_id).original_process_graph

    ##########################################################
    # Optimized graph
    ##########################################################

    def update_optimized_graph(self, user_id: str, graph: list[dict]):
        """
        Store the optimized process graph.

        Parameters
        ----------
        user_id : str
            User identifier.

        graph : list[dict]
            Optimized process graph generated by the optimizer.
        """
        session = self.get_session(user_id)
        session.optimized_process_graph = graph

    def get_optimized_graph(self, user_id: str) -> Optional[list[dict]]:
        """
        Retrieve the optimized process graph.

        Parameters
        ----------
        user_id : str
            User identifier.

        Returns
        -------
        Optional[list[dict]]
            Optimized graph or None.
        """
        return self.get_session(user_id).optimized_process_graph

    ##########################################################
    # Chat memory
    ##########################################################

    def add_user_message(self, user_id: str, message: str):
        """
        Add a user message to conversation history.

        Parameters
        ----------
        user_id : str
            User identifier.

        message : str
            Message text.
        """
        session = self.get_session(user_id)

        session.chat_history.append(ChatMessage(role="user", content=message))

    def add_assistant_message(self, user_id: str, message: str):
        """
        Add an assistant response to conversation history.

        Parameters
        ----------
        user_id : str
            User identifier.

        message : str
            Assistant response.
        """
        session = self.get_session(user_id)

        session.chat_history.append(ChatMessage(role="assistant", content=message))

    def get_chat_history(self, user_id: str) -> list[ChatMessage]:
        """
        Retrieve complete conversation history.

        Parameters
        ----------
        user_id : str
            User identifier.

        Returns
        -------
        list[ChatMessage]
            All messages exchanged with the user.
        """
        return self.get_session(user_id).chat_history

    ##########################################################
    # Build LLM context
    ##########################################################

    def build_context(self, user_id: str, last_n_messages: int = 10) -> str:
        """
        Build a text context from recent chat messages.

        This context can be directly inserted into prompts
        for answering follow-up questions.

        Parameters
        ----------
        user_id : str
            User identifier.

        last_n_messages : int, default=10
            Number of recent messages to include.

        Returns
        -------
        str
            Formatted conversation history.
        """
        session = self.get_session(user_id)

        history = session.chat_history[-last_n_messages:]

        context = []

        for msg in history:
            context.append(f"{msg.role}: {msg.content}")

        return "\n".join(context)

    ##########################################################
    # Clear session
    ##########################################################

    def clear_session(self, user_id: str):
        """
        Remove all information associated with a user.

        Parameters
        ----------
        user_id : str
            User identifier.

        Notes
        -----
        This deletes:
        - Original graph
        - Optimized graph
        - Chat history
        """
        with self.lock:

            if user_id in self.sessions:
                del self.sessions[user_id]

    def build_full_context(self, user_id: str, last_n_messages: int = 10):

        session = self.get_session(user_id)

        return f"""
    Original Process Graph:
    {json.dumps(session.original_process_graph, indent=2)}

    Optimized Process Graph:
    {json.dumps(session.optimized_process_graph, indent=2)}

    Conversation History:
    {self.build_context(user_id, last_n_messages)}
    """

    async def _generate_response(self, prompt: str) -> str:
        response = await self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a helpful process optimization assistant.\n"
                        "Answer questions using the original process graph, "
                        "optimized process graph, and conversation history.\n\n"
                        "Guidelines:\n"
                        "- Keep answers short and easy to understand.\n"
                        "- Use simple language suitable for non-experts.\n"
                        "- Avoid technical jargon unless necessary.\n"
                        "- Explain benefits and changes clearly.\n"
                        "- Use bullet points when helpful.\n"
                        "- Limit responses to 3-5 sentences unless the user asks for more details."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
        )

        return response.choices[0].message.content

    async def chat(self, user_id: str, message: str) -> str:
        """
        Main conversational interface.
        """

        # store user message
        self.add_user_message(user_id, message)

        context = self.build_full_context(user_id, last_n_messages=10)

        prompt = f"""
    {context}

    User Question:
    {message}
    """

        response = await self._generate_response(prompt)

        # store assistant message
        self.add_assistant_message(user_id, response)

        return response
