"""
===============================================================================
Process Extractor
===============================================================================

This module extracts industrial process information from text documents and
converts it into structured JSON using an OpenAI language model.

Supported input formats
-----------------------
- TXT
- Markdown (.md)
- Microsoft Word (.docx)
- PDF

The extracted output follows a structured schema describing:

- Process metadata
- Inputs and outputs
- By-products
- Energy consumption
- Water usage
- Emissions
- Cost information
- Process dependencies

The OpenAI API key is automatically loaded from the
OPENAI_API_KEY environment variable.

Example
-------
extractor = ProcessExtractor()

processes = extractor.extract_processes("plant_processes.docx")

extractor.save_json(
    "plant_processes.docx",
    "processes.json"
)
===============================================================================
"""

from pathlib import Path
import json
from langchain_openai import ChatOpenAI

import docx
from pypdf import PdfReader
import os

from typing import List
from pydantic import BaseModel


###############################################################################
# Structured Output Models
#
# These Pydantic models define the schema returned by the LLM. They are used
# to enforce type safety and guarantee that the extracted data conforms to
# the expected structure.
###############################################################################
class Energy(BaseModel):
    """
    Represents energy consumed by a process step.

    Attributes
    ----------
    source : str
        Energy source (electricity, steam, natural gas, etc.).

    quantity : str
        Amount of energy consumed including units.
    """

    source: str
    quantity: str


class Water(BaseModel):
    """
    Represents water usage information for a process.

    Attributes
    ----------
    intake : str
        Water consumed by the process.

    discharge : str
        Water discharged after processing.
    """

    intake: str
    discharge: str


class Emissions(BaseModel):
    """
    Represents emissions generated by a process step.

    Attributes
    ----------
    co2 : str
        Carbon dioxide emissions.

    methane : str
        Methane emissions.

    nox : str
        Nitrogen oxide emissions.

    sox : str
        Sulfur oxide emissions.

    particulate : str
        Particulate matter emissions.
    """

    co2: str
    methane: str
    nox: str
    sox: str
    particulate: str


class ProcessStep(BaseModel):
    """
    Represents one industrial process stage.

    A process stage contains material flow information, utility
    consumption and environmental impact data.

    Attributes
    ----------
    id : int
        Sequential process identifier.

    process_name : str
        Name of the process.

    description : str
        Detailed explanation of the process.

    inputs : List[str]
        Raw materials entering the process.

    outputs : List[str]
        Products generated by the process.

    byproducts : List[str]
        Secondary outputs generated.

    energy : Energy
        Energy consumption information.

    water : Water
        Water intake and discharge data.

    emissions : Emissions
        Environmental emissions.

    cost : str
        Estimated process cost.

    next_processes : List[str]
        Downstream processes connected to this step.
    """

    id: int
    process_name: str
    description: str

    inputs: List[str]
    outputs: List[str]
    byproducts: List[str]

    energy: Energy
    water: Water
    emissions: Emissions

    cost: str
    next_processes: List[str]


class ProcessList(BaseModel):
    """
    Wrapper model representing the complete set of process steps
    extracted from a document.
    """

    processes: List[ProcessStep]


class ProcessExtractor:
    """
    Extracts industrial process information from documents using OpenAI.

    Features
    --------
    - Supports TXT, MD, DOCX and PDF files.
    - Uses LangChain structured output.
    - Produces strongly typed JSON data.
    - Automatically loads the API key from the environment.

    Parameters
    ----------
    model : str
        OpenAI model to use for extraction.

    Raises
    ------
    ValueError
        If OPENAI_API_KEY is not defined.
    """

    def __init__(self, model: str = "gpt-4o"):
        """
        Initialize the extractor and create the OpenAI client.

        Parameters
        ----------
        model : str
            OpenAI model name.

        Raises
        ------
        ValueError
            If OPENAI_API_KEY is not available.
        """
        api_key = os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise ValueError("OPENAI_API_KEY environment variable is not set.")

        self.llm = ChatOpenAI(model=model, temperature=0)

    ###############################################################################
    # File Readers
    #
    # These helper functions convert various document formats into plain text.
    # All extracted text is later supplied to the language model.
    ###############################################################################

    def _load_txt(self, filepath: str) -> str:
        """
        Read a text file.

        Parameters
        ----------
        filepath : str
            Path to the .txt file.

        Returns
        -------
        str
            File contents.
        """
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()

    def _load_md(self, filepath: str) -> str:
        """
        Read a markdown file and return its contents.
        """
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()

    def _load_docx(self, filepath: str) -> str:
        """
        Extract all paragraph text from a Word document.

        Parameters
        ----------
        filepath : str
            Path to the DOCX file.

        Returns
        -------
        str
            Combined document text.
        """
        doc = docx.Document(filepath)
        return "\n".join([p.text for p in doc.paragraphs])

    def _load_pdf(self, filepath: str) -> str:
        """
        Extract text from every page of a PDF document.

        Parameters
        ----------
        filepath : str
            Path to the PDF file.

        Returns
        -------
        str
            Concatenated page contents.
        """
        reader = PdfReader(filepath)

        pages = []
        for page in reader.pages:
            text = page.extract_text()
            if text:
                pages.append(text)

        return "\n".join(pages)

    ###############################################################################
    # Document Loader
    #
    # Determines the file type and dispatches loading to the appropriate reader.
    ###############################################################################

    def load_file(self, filepath: str) -> str:
        """
        Load text from a supported document.

        Supported formats
        -----------------
        - .txt
        - .md
        - .docx
        - .pdf

        Parameters
        ----------
        filepath : str
            Input document path.

        Returns
        -------
        str
            Extracted text.

        Raises
        ------
        ValueError
            If the file extension is unsupported.
        """

        suffix = Path(filepath).suffix.lower()

        loaders = {
            ".txt": self._load_txt,
            ".md": self._load_md,
            ".docx": self._load_docx,
            ".pdf": self._load_pdf,
        }

        if suffix not in loaders:
            raise ValueError(f"Unsupported format: {suffix}")

        return loaders[suffix](filepath)

    ###############################################################################
    # Process Extraction
    #
    # Converts raw document text into structured process information using
    # LangChain structured output and Pydantic schemas.
    ###############################################################################

    def extract_processes(self, filepath: str):
        """
        Extract industrial process steps from a document.

        The document is first converted to text and then passed to the
        language model. The model returns data that conforms to the
        ProcessList schema.

        Parameters
        ----------
        filepath : str
            Input document path.

        Returns
        -------
        list[dict]
            List of extracted process dictionaries.
        """

        document_text = self.load_file(filepath)

        structured_llm = self.llm.with_structured_output(ProcessList)

        prompt = f"""
    Extract every industrial process step from the document.

    Rules:
    - Preserve process ordering.
    - Preserve process names exactly.
    - Preserve units.
    - next_processes should contain process names.
    - Return an empty list if no processes exist.

    Document:

    {document_text}
    """

        result = structured_llm.invoke(prompt)

        return [p.model_dump() for p in result.processes]

    ###############################################################################
    # Export Utilities
    #
    # Functions for writing extracted process data to external files.
    ###############################################################################

    def save_json(self, filepath: str, output_path: str):
        """
        Extract process information and save it as a JSON file.

        Parameters
        ----------
        filepath : str
            Source document.

        output_path : str
            Destination JSON file.

        Returns
        -------
        list[dict]
            Extracted process data.
        """
        processes = self.extract_processes(filepath)

        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(processes, f, indent=4, ensure_ascii=False)

        return processes