"""
schemas.py

Data models used for representing extracted manufacturing or industrial
process information.

These Pydantic schemas define the structure expected from the LLM output
and are used for validation, serialization, and communication between
backend services and the frontend dashboard.

Main Components
---------------
ProcessStep
    Represents a single process with its inputs, outputs, resource
    consumption, emissions, and connections to subsequent processes.

ProcessList
    Container object holding all extracted process steps.
"""

from pydantic import BaseModel
from typing import List


class ProcessStep(BaseModel):
    """
    Represents one process or operation in the process chain.

    Each instance contains the resources consumed, products generated,
    environmental impacts, and links to downstream processes.
    """

    # Unique identifier for the process step
    id: int
    # Name of the process or operation
    process_name: str
    # Brief description of what the process performs
    description: str
    # Materials or components required as inputs
    inputs: List[str]
    # Main products generated by the process
    outputs: List[str]
    # Secondary products or waste streams produced
    byproducts: List[str]
    # Raw materials consumed in the process
    raw_materials: List[str]
    # Energy usage information
    energy_consumption: str
    # Water usage information
    water_consumption: str
    # Pollutants or emissions released during the process
    emissions: List[str]
    # Estimated operating cost of the process
    operating_cost: str
    # Names or identifiers of subsequent processes
    next_processes: List[str]


class ProcessList(BaseModel):
    processes: List[ProcessStep]
