"""
schemas.py

Pydantic data models used for representing extracted manufacturing,
industrial, or process-chain information.

These schemas define the structured format expected from the LLM output
and are used for:

- Validation of extracted process information.
- Serialization and API communication.
- Storage and transfer between backend services.
- Visualization in dashboards and process-flow applications.

Main Components
---------------
ProcessInput
    Material, component, or resource consumed by a process.

ProcessOutput
    Product, intermediate product, waste stream, or byproduct
    generated by a process.

Emission
    Atmospheric emissions or pollutants released by a process.

Energy
    Energy consumed by a process together with its source.

Water
    Water consumed by a process together with its source.

ProcessStep
    Represents one operation or stage in a manufacturing or industrial
    process chain, including resource consumption, outputs, emissions,
    and links to downstream processes.

ProcessList
    Container object holding all extracted process steps.
"""

from pydantic import BaseModel
from typing import List


class ProcessInput(BaseModel):
    """
    Represents a material or resource consumed by a process.

    Attributes
    ----------
    name : str
        Name of the input material or resource.
    quantity : float
        Amount consumed.
    measuring_unit : str
        Unit associated with the quantity.
    """

    name: str
    quantity: float
    measuring_unit: str


class ProcessOutput(BaseModel):
    """
    Represents a product, intermediate product, or waste stream
    generated by a process.

    Attributes
    ----------
    name : str
        Name of the output material.
    quantity : float
        Amount produced.
    measuring_unit : str
        Unit associated with the quantity.
    """

    name: str
    quantity: float
    measuring_unit: str


class Emission(BaseModel):
    """
    Represents an emission or pollutant released during a process.

    Attributes
    ----------
    name : str
        Name of the emitted substance.
    quantity : float
        Amount emitted.
    measuring_unit : str
        Unit associated with the quantity.
    """

    name: str
    quantity: float
    measuring_unit: str


class Energy(BaseModel):
    """
    Represents energy consumed during a process.

    Attributes
    ----------
    name : str
        Type of energy consumed.
    quantity : float
        Amount of energy used.
    measuring_unit : str
        Unit of measurement.
    energy_source : str
        Source of energy (e.g., Grid Electricity, Natural Gas,
        Solar Power, Diesel).
    """

    name: str
    quantity: float
    measuring_unit: str
    energy_source: str


class Water(BaseModel):
    """
    Represents water consumption during a process.

    Attributes
    ----------
    quantity : float
        Amount of water consumed.
    measuring_unit : str
        Unit associated with the quantity.
    water_source : str
        Source of water (e.g., Municipal Supply, Groundwater,
        Recycled Water).
    """

    quantity: float
    measuring_unit: str
    water_source: str


class ProcessStep(BaseModel):
    """
    Represents a single process or operation in a process chain.

    Each process contains information about:

    - Materials and resources consumed.
    - Products and byproducts generated.
    - Energy and water requirements.
    - Environmental emissions.
    - Operating cost.
    - Connections to subsequent processes.

    Together, these attributes provide a complete representation
    of a manufacturing or industrial operation.
    """

    # Unique identifier for the process step
    id: int
    # Name of the process or operation
    process_name: str
    # Brief explanation of the activities performed in this step
    description: str

    # Materials, components, or resources required by the process
    inputs: List[ProcessInput]
    # Main products generated by the process
    outputs: List[ProcessOutput]
    # Secondary products, waste streams, or recoverable materials
    byproducts: List[ProcessOutput]
    # List of all energy types consumed by the process
    energy_consumption: List[Energy]
    # List of water sources and corresponding consumption amounts
    water_consumption: List[Water]
    # Pollutants or greenhouse gas emissions generated
    emissions: List[Emission]
    # Estimated operating cost of the process
    operating_cost: str
    # Names or identifiers of downstream processes
    next_processes: List[str]


class ProcessList(BaseModel):
    processes: List[ProcessStep]
